/**
 * @file サイドバー構成を定義する設定ファイル。
 * @summary ドキュメントの階層構造やナビゲーションを管理し、自動生成と手動定義に対応する。
 * @limitation 制限事項: サイドバーのロケール別設定や高度な権限制御は未実装。
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * @description サイトで利用するサイドバー定義。既定ではファイルシステム構造から自動生成する。
 * @spec 主要仕様:
 * - docs ディレクトリを走査し、自動的にサイドバーを生成
 * - コメントアウト部分を有効化することで手動定義も可能
 * @limitation 制限事項: 現状は単一サイドバー構成のみ定義し、複数サイドバーの同時利用例は未掲載。
 */
const sidebars: SidebarsConfig = {
  // 既定では docs フォルダーの構造をもとにサイドバーを自動生成する
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 必要に応じてサイドバーを手動で定義することも可能
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'チュートリアル',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
